In [6]:
import numpy as np
marks=np.array([[90,98,97],[80,81,92],[75,74,72]],np.int32)
#print the datatype of elements
print(marks.dtype)
#print the shape
print(marks.shape)
#print the mark in first row second column
print(marks[0,1])
#print the 1st column
print(marks[:,0])
#copy the 1st column to quarterly
quarterly=marks[:,0]
#change the mark in the 1st row 1st column in quarterly and it will also affects marks
quarterly[0]=92
print(quarterly)
print(marks)

int32
(3, 3)
98
[90 80 75]
[92 80 75]
[[92 98 97]
 [80 81 92]
 [75 74 72]]


In [13]:
#ndim gives the dimension of array
print(marks.ndim)
#zeros()fills the element with zero
print(np.zeros((2,3,4)).ndim)
print(np.zeros((2,3)))
#T gives the transposed array
print(marks.T)
#reaal & imaginary gives real&imaginary value
x=np.array([1+0j,2+1j])
print(x.real)
print(x.imag)

2
3
[[0. 0. 0.]
 [0. 0. 0.]]
[[92 80 75]
 [98 81 74]
 [97 92 72]]
[1. 2.]
[0. 1.]


In [11]:
import numpy as np
#flat is an 1D iterator
a=np.arange(1,7)
print(a)
a=a.reshape(2,3)
print(a)
print(a.flat[3])
print(a.T)
print(a.T.flat[4])
a.flat=3
print(a)
#make the 3nd element and 5th element as 1
a.flat[[2,4]]=1
print(a)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
4
[[1 4]
 [2 5]
 [3 6]]
3
[[3 3 3]
 [3 3 3]]
[[3 3 1]
 [3 1 3]]


In [7]:
import numpy as np
mark=np.array([[98,97,95],[78,75,74]])
mark1=np.array([[90,92,91],[68,35,73]])
print(mark.__ge__(90))
b=1
c=-1
print(b.__bool__())
print(b.__neg__())
print(c.__abs__())
print(mark.__invert__())
print(mark.__add__(2))
print(mark.__truediv__(2))
print(mark.__floordiv__(2))
print(mark.__mod__(2))
print(mark.__pow__(3))
# p=[[1,2,3], [2,3,4]]
# q=[[1,2,3], [2,3,4]]
# print(np.dot(p, q))
p= [[1, 2], [4, 1]]  
q = [[4, 11], [2, 3]]  
r=np.dot(p, q)  
print(r)
arr=np.array([[2,3,4],[5,1,2]])
s=arr.__copy__()
print(s)
s[0][1]=10
print(arr)
print(s.item(0))
print(s.item(1,0))


[[ True  True  True]
 [False False False]]
True
-1
1
[[-99 -98 -96]
 [-79 -76 -75]]
[[100  99  97]
 [ 80  77  76]]
[[49.  48.5 47.5]
 [39.  37.5 37. ]]
[[49 48 47]
 [39 37 37]]
[[0 1 1]
 [0 1 0]]
[[941192 912673 857375]
 [474552 421875 405224]]
[[ 8 17]
 [18 47]]
[[2 3 4]
 [5 1 2]]
[[2 3 4]
 [5 1 2]]
2
5


In [33]:
a1=np.array([[2,4,5,6],[1,3,5,7]])
print(a1[a1>3])
print(a1[a1>3].sum())
print(a1)
print(np.all(a1>3))
print(np.all(a1>3,axis=0))
print(np.all(a1>3,axis=1))
print(a1[:,np.all(a1>3,axis=0)])
print(a1[np.all(a1>3,axis=1),:])
print(a1[np.all(a1 < 7, axis=1), :])
print(a1[np.any(a1>4,axis=1)])
#print(a[np.any(a < 5, axis=1)])
print(a1[~np.any(a1>6,axis=1)])
#print(a[~np.any(a < 5, axis=1)])
print(np.delete(a1,0,axis=0))
print(np.delete(a1,0,axis=1))
print(np.where(a1>5))
print(a1[(a1>4)&(a1%2==0)])

[4 5 6 5 7]
27
[[2 4 5 6]
 [1 3 5 7]]
False
[False False  True  True]
[False False]
[[5 6]
 [5 7]]
[]
[[2 4 5 6]]
[[2 4 5 6]
 [1 3 5 7]]
[[2 4 5 6]]
[[1 3 5 7]]
[[4 5 6]
 [3 5 7]]
(array([0, 1]), array([3, 3]))
[6]
